create TABLE project.S_USER (
  ID_S_USER BIGINT(20) NOT NULL AUTO_INCREMENT,
  SSO_TOKEN VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  FIRST_NAME VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  LAST_NAME VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  EMAIL_NOTIFIED VARCHAR(508) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  USER_NAME VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  ID_S_USER_CREATE BIGINT(20) DEFAULT NULL,
  ID_S_USER_MOD BIGINT(20) DEFAULT NULL,
  ID_S_USER_STORNO BIGINT(20) DEFAULT NULL,
  STORNO BIGINT(20) NOT NULL DEFAULT 0,
  ID_S_USER_VALID BIGINT(20) DEFAULT NULL,
  ARCHIVE_DATE DATE DEFAULT NULL,
  CREATE_DATE TIMESTAMP NULL DEFAULT NULL,
  LAST_DML_TIME TIMESTAMP NULL DEFAULT NULL,
  MOD_DATE TIMESTAMP NULL DEFAULT NULL,
  STORNO_DATE TIMESTAMP NULL DEFAULT NULL,
  VALID_FROM TIMESTAMP NULL DEFAULT NULL,
  VALID_TO TIMESTAMP NULL DEFAULT NULL,
  VALID BIGINT(20) DEFAULT NULL,
  VALID_ID_S_USER BIGINT(20) DEFAULT NULL,
  VALID_TIME DATETIME DEFAULT NULL,
  MOBILE_PHONE VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  CURRENT_SESSION_ID VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  AVATAR LONGBLOB DEFAULT NULL,
  ID_AVATAR BIGINT(20) DEFAULT NULL,
  BANNED BIGINT(20) DEFAULT NULL,
  ID_DOCUMENT_PROFILE VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ID_INTL_LANGUAGE BIGINT(19) DEFAULT 2,
  VALID_FROM_COMM VARCHAR(4000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  VALID_TO_COMM VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  BANNED_COMM VARCHAR(4000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  SECRET_KEY VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  USER_PASSWORD VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  USER_PASSWORD_TEMP VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ACTIVATED_FROM DATETIME DEFAULT NULL,
  ACTIVATED_TO DATETIME DEFAULT NULL,
  WRONG_PASSW BIGINT(20) DEFAULT NULL,
  USER_PASSWORD_VALID_TO DATETIME DEFAULT NULL,
  TWO_FA BIGINT(20) DEFAULT NULL,
  ID_NOTIFICATION_TYPE BIGINT(20) DEFAULT NULL,
  LDAP BIGINT(20) DEFAULT NULL,
  USER_COMMENT VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  USER_PASSWORD_RETYPE VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ID_S_USER_ACTIVATE BIGINT(20) DEFAULT NULL,
  ID_S_USER_INACTIVATE BIGINT(20) DEFAULT NULL,
  ID_S_USER_WRONG_PWD BIGINT(20) DEFAULT NULL,
  ID_STATUS BIGINT(19) DEFAULT NULL,
  VEZETEKNEV VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  KERESZTNEV VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  VALIDATION_DATE DATETIME DEFAULT NULL,
  VALIDATION_ERR_COUNT BIGINT(20) DEFAULT NULL,
  VALIDATION_MESSAGE TEXT DEFAULT NULL,
  VALIDATION_WARN_COUNT BIGINT(20) DEFAULT NULL,
  GDPR_TORLES TIMESTAMP NULL DEFAULT NULL,
  LAST_VERSION_DATE DATETIME DEFAULT NULL,
  LAST_LOGIN_TIME DATETIME DEFAULT NULL,
  ID_DOCUMENT_AVATAR VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (ID_S_USER)
)
ENGINE = INNODB,
AUTO_INCREMENT = 0,
AVG_ROW_LENGTH = 244,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_AVATAR(ID_AVATAR);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_NOTIFICATION_TYPE(ID_NOTIFICATION_TYPE);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_ACTIVATE(ID_S_USER_ACTIVATE);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_CREATE(ID_S_USER_CREATE);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_INACTIVATE(ID_S_USER_INACTIVATE);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_MOD(ID_S_USER_MOD);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_STORNO(ID_S_USER_STORNO);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_VALID(ID_S_USER_VALID);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_ID_S_USER_WRONG_PWD(ID_S_USER_WRONG_PWD);

ALTER TABLE project.S_USER 
  ADD INDEX IDX_S_USER_USER_NAME(USER_NAME);

ALTER TABLE project.S_USER 
  ADD INDEX S_USER_ibfk_1(ID_INTL_LANGUAGE);

ALTER TABLE project.S_USER 
  ADD CONSTRAINT FK_GEN155238702923769187637321147798 FOREIGN KEY (ID_STATUS)
    REFERENCES project.ST_S_USER(ID_ST_S_USER);

ALTER TABLE project.S_USER 
  ADD CONSTRAINT FK_S_USER_ID_S_USER_CREATE FOREIGN KEY (ID_S_USER_CREATE)
    REFERENCES project.S_USER(ID_S_USER) ON delete SET NULL;

ALTER TABLE project.S_USER 
  ADD CONSTRAINT FK_S_USER_ID_S_USER_MOD FOREIGN KEY (ID_S_USER_MOD)
    REFERENCES project.S_USER(ID_S_USER) ON delete SET NULL;

ALTER TABLE project.S_USER 
  ADD CONSTRAINT FK_S_USER_ID_S_USER_STORNO FOREIGN KEY (ID_S_USER_STORNO)
    REFERENCES project.S_USER(ID_S_USER) ON delete SET NULL;

insert into project.S_USER (ID_S_USER, SSO_TOKEN, FIRST_NAME, LAST_NAME, EMAIL_NOTIFIED, USER_NAME, ID_S_USER_CREATE, ID_S_USER_MOD, ID_S_USER_STORNO, STORNO, ID_S_USER_VALID, ARCHIVE_DATE, CREATE_DATE, LAST_DML_TIME, MOD_DATE, STORNO_DATE, VALID_FROM, VALID_TO, VALID, VALID_ID_S_USER, VALID_TIME, MOBILE_PHONE, CURRENT_SESSION_ID, AVATAR, ID_AVATAR, BANNED, ID_DOCUMENT_PROFILE, ID_INTL_LANGUAGE, VALID_FROM_COMM, VALID_TO_COMM, BANNED_COMM, SECRET_KEY, USER_PASSWORD, USER_PASSWORD_TEMP, ACTIVATED_FROM, ACTIVATED_TO, WRONG_PASSW, USER_PASSWORD_VALID_TO, TWO_FA, ID_NOTIFICATION_TYPE, LDAP, USER_COMMENT, USER_PASSWORD_RETYPE, ID_S_USER_ACTIVATE, ID_S_USER_INACTIVATE, ID_S_USER_WRONG_PWD, ID_STATUS, VEZETEKNEV, KERESZTNEV, VALIDATION_DATE, VALIDATION_ERR_COUNT, VALIDATION_MESSAGE, VALIDATION_WARN_COUNT, GDPR_TORLES, LAST_VERSION_DATE, LAST_LOGIN_TIME, ID_DOCUMENT_AVATAR) values (15404, 'x2bOfZq-UnXHY04KTWHKXAafYdFKCl9E15404', null, null, 'Galambos.Laszlo@zip2000.hu', 'galambos.laszlo', null, null, null, 0, null, null, '2015-12-18 00:00:00', '2020-08-05 12:32:10', '2020-08-05 12:32:10', null, null, null, 1, null, null, '36 30 927-3843', null, null, null, 0, null, 2, null, null, null, '5mDKFaaFMnRPnX9P8GfWI7_MOhEv_ame15404', null, null, '2015-12-17 22:00:00', null, 0, null, 0, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2020-08-05 12:32:11', '5c910793a6c219d73a2e230e');